### ISSUE TITLE
AppImage 0.5.5 fails on startup with "Image could not be created from .../appicon.png"

### ISSUE THREAD

**Issue by magv** [glyphr-studio/Glyphr-Studio-Desktop#56]
Hi, folks. Running `./Glyphr.Studio-0.5.5.AppImage` on my machine (Ubuntu 18.04) results in an empty Electron window and a message box saying:
```
Uncaught Exception:
Error: Image could not be created from /tmp/.mount_XXX/resources/app.asar/images/appicon.png
  at App.createWindow(/tmp/.mount_XXX/resources/app.asar.main.js:100:9)
  at App.emit(events.js:223:5)
```

The previous release (0.5.4) works fine.

**Comment by pludi** [comment]
Same error with the `.deb`:
```
Uncaught Exception:
Error: Image could not be created from /opt/Glyphr Studio/resources/app.asar/images/appicon.png
  at App.createWindow (/opt/Glyphr Studio/resources/app.asar/main.js:100:9)
  at App.emit(events.js:223:5)
```
